version: "3"
services:
  db:
    image: postgres:latest
    container_name: twitter-x-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Twitter-X-Recreation-DB
    ports:
      - "5432:5432"
